### ISSUE TITLE
Let users change their own address and/or email

### ISSUE THREAD

**Issue by filiptypjeu** [Teknologforeningen/teknologr.io#194]

**Comment by djstockma** [comment]
Provide a page for users to edit their own personal information. Fields that users could change themselves include:
* Gatuaddress
* Postnummer
* Postanstalt
* Land
* Telefonnummer
* Epost
* Vill ha modulen hemskickad (alternatively this could be done as a separate function: prenumerera / avprenumerera på modulen, but I think e checkbox works fine
* Studentbladet (same as modulen, if this is even relevant?)

**Comment by tlangens** [comment]
Note that before we allow this, there ought to be thorough validation in place, i.e. ensuring that the address is valid and exists. It has apparently been problematic before that people have changed their contact information incorrectly and so mail has been incorrectly delivered for years until the error was noticed.

**Comment by filiptypjeu** [comment]
Sounds to me like the user's own problem if he updates his email to a faulty one... Faulty emails can slip through in the current process as well, but most faulty emails are old university domain emails that people have lost access to.

**Comment by filiptypjeu** [comment]
I see now that you were talking about mail, not email, but my reasoning still applies.

**Comment by tlangens** [comment]
IIRC there was some valid reasoning why we wanted the address changes to pass through human validation before being stored in the DB, so better check with Kansliet to get all the requirements sorted out first.
I think it would be in TF:s interest to prevent incorrect addresses in the registry as much as possible, as errors there might not be noticed for a long time or maybe ever. Unless it's too much hassle we might use e.g. [Google's address validation API](https://developers.google.com/maps/documentation/address-validation) in the client before submitting the result.

**Comment by tlangens** [comment]
Another thing worth considering might be storing history, so we can see what addresses people have used earlier.
One issue that I think we used to have was that as people updated certain fields like email, they would leave others empty, which in turn erased those values from the DB. That is probably more the fault of a bad client implementation though.

**Comment by djstockma** [comment]
I checked with kansliet and they see no specific reason that this wouldn't be possible. Some type of validations for addresses (street and email) would definitely be good, but right now changes made to addresses etc (submitted by a form) aren't checked very closely either.
